// Search
export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST'
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS'
export const SEARCH_MEDIA_FAILURE = 'SEARCH_MEDIA_FAILURE'

// Posts
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'

// Single Post
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'
